// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pb/vasystem/api/v2/aircraft.proto

package vasystemapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AircraftType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IcaoCode string `protobuf:"bytes,2,opt,name=icao_code,json=icaoCode,proto3" json:"icao_code,omitempty"`
	IataCode string `protobuf:"bytes,3,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	Name     string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AircraftType) Reset() {
	*x = AircraftType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_vasystem_api_v2_aircraft_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AircraftType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AircraftType) ProtoMessage() {}

func (x *AircraftType) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vasystem_api_v2_aircraft_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AircraftType.ProtoReflect.Descriptor instead.
func (*AircraftType) Descriptor() ([]byte, []int) {
	return file_pb_vasystem_api_v2_aircraft_proto_rawDescGZIP(), []int{0}
}

func (x *AircraftType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AircraftType) GetIcaoCode() string {
	if x != nil {
		return x.IcaoCode
	}
	return ""
}

func (x *AircraftType) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *AircraftType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AircraftModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AircraftType *AircraftType `protobuf:"bytes,2,opt,name=aircraft_type,json=aircraftType,proto3" json:"aircraft_type,omitempty"`
	Airline      *Airline      `protobuf:"bytes,3,opt,name=airline,proto3" json:"airline,omitempty"`
	Name         string        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AircraftModel) Reset() {
	*x = AircraftModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_vasystem_api_v2_aircraft_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AircraftModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AircraftModel) ProtoMessage() {}

func (x *AircraftModel) ProtoReflect() protoreflect.Message {
	mi := &file_pb_vasystem_api_v2_aircraft_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AircraftModel.ProtoReflect.Descriptor instead.
func (*AircraftModel) Descriptor() ([]byte, []int) {
	return file_pb_vasystem_api_v2_aircraft_proto_rawDescGZIP(), []int{1}
}

func (x *AircraftModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AircraftModel) GetAircraftType() *AircraftType {
	if x != nil {
		return x.AircraftType
	}
	return nil
}

func (x *AircraftModel) GetAirline() *Airline {
	if x != nil {
		return x.Airline
	}
	return nil
}

func (x *AircraftModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pb_vasystem_api_v2_aircraft_proto protoreflect.FileDescriptor

var file_pb_vasystem_api_v2_aircraft_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x62, 0x2f, 0x76, 0x61, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x76, 0x61, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x32, 0x1a, 0x21, 0x70, 0x62, 0x2f, 0x76, 0x61, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0c, 0x41, 0x69, 0x72, 0x63, 0x72,
	0x61, 0x66, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x63, 0x61, 0x6f, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x63, 0x61, 0x6f,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x0d, 0x41, 0x69, 0x72, 0x63, 0x72, 0x61,
	0x66, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x42, 0x0a, 0x0d, 0x61, 0x69, 0x72, 0x63, 0x72,
	0x61, 0x66, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x76, 0x61, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32,
	0x2e, 0x41, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x61,
	0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x61,
	0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76,
	0x61, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32, 0x2e, 0x41,
	0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x61, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x76, 0x61, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2d,
	0x61, 0x70, 0x69, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x67, 0x6f, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x61, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x3b, 0x76, 0x61, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_vasystem_api_v2_aircraft_proto_rawDescOnce sync.Once
	file_pb_vasystem_api_v2_aircraft_proto_rawDescData = file_pb_vasystem_api_v2_aircraft_proto_rawDesc
)

func file_pb_vasystem_api_v2_aircraft_proto_rawDescGZIP() []byte {
	file_pb_vasystem_api_v2_aircraft_proto_rawDescOnce.Do(func() {
		file_pb_vasystem_api_v2_aircraft_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_vasystem_api_v2_aircraft_proto_rawDescData)
	})
	return file_pb_vasystem_api_v2_aircraft_proto_rawDescData
}

var file_pb_vasystem_api_v2_aircraft_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_vasystem_api_v2_aircraft_proto_goTypes = []interface{}{
	(*AircraftType)(nil),  // 0: vasystem.api.v2.AircraftType
	(*AircraftModel)(nil), // 1: vasystem.api.v2.AircraftModel
	(*Airline)(nil),       // 2: vasystem.api.v2.Airline
}
var file_pb_vasystem_api_v2_aircraft_proto_depIdxs = []int32{
	0, // 0: vasystem.api.v2.AircraftModel.aircraft_type:type_name -> vasystem.api.v2.AircraftType
	2, // 1: vasystem.api.v2.AircraftModel.airline:type_name -> vasystem.api.v2.Airline
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_vasystem_api_v2_aircraft_proto_init() }
func file_pb_vasystem_api_v2_aircraft_proto_init() {
	if File_pb_vasystem_api_v2_aircraft_proto != nil {
		return
	}
	file_pb_vasystem_api_v2_airlines_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_vasystem_api_v2_aircraft_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AircraftType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_vasystem_api_v2_aircraft_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AircraftModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_vasystem_api_v2_aircraft_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_vasystem_api_v2_aircraft_proto_goTypes,
		DependencyIndexes: file_pb_vasystem_api_v2_aircraft_proto_depIdxs,
		MessageInfos:      file_pb_vasystem_api_v2_aircraft_proto_msgTypes,
	}.Build()
	File_pb_vasystem_api_v2_aircraft_proto = out.File
	file_pb_vasystem_api_v2_aircraft_proto_rawDesc = nil
	file_pb_vasystem_api_v2_aircraft_proto_goTypes = nil
	file_pb_vasystem_api_v2_aircraft_proto_depIdxs = nil
}
