// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: pb/vasystem/api/v2/airlines.proto

package apiv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AirlinesServiceClient is the client API for AirlinesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirlinesServiceClient interface {
	// List airlines
	ListAirlines(ctx context.Context, in *ListAirlinesRequest, opts ...grpc.CallOption) (*ListAirlinesResponse, error)
}

type airlinesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAirlinesServiceClient(cc grpc.ClientConnInterface) AirlinesServiceClient {
	return &airlinesServiceClient{cc}
}

func (c *airlinesServiceClient) ListAirlines(ctx context.Context, in *ListAirlinesRequest, opts ...grpc.CallOption) (*ListAirlinesResponse, error) {
	out := new(ListAirlinesResponse)
	err := c.cc.Invoke(ctx, "/vasystem.api.v2.AirlinesService/ListAirlines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AirlinesServiceServer is the server API for AirlinesService service.
// All implementations must embed UnimplementedAirlinesServiceServer
// for forward compatibility
type AirlinesServiceServer interface {
	// List airlines
	ListAirlines(context.Context, *ListAirlinesRequest) (*ListAirlinesResponse, error)
	mustEmbedUnimplementedAirlinesServiceServer()
}

// UnimplementedAirlinesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAirlinesServiceServer struct {
}

func (UnimplementedAirlinesServiceServer) ListAirlines(context.Context, *ListAirlinesRequest) (*ListAirlinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAirlines not implemented")
}
func (UnimplementedAirlinesServiceServer) mustEmbedUnimplementedAirlinesServiceServer() {}

// UnsafeAirlinesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirlinesServiceServer will
// result in compilation errors.
type UnsafeAirlinesServiceServer interface {
	mustEmbedUnimplementedAirlinesServiceServer()
}

func RegisterAirlinesServiceServer(s grpc.ServiceRegistrar, srv AirlinesServiceServer) {
	s.RegisterService(&AirlinesService_ServiceDesc, srv)
}

func _AirlinesService_ListAirlines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAirlinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirlinesServiceServer).ListAirlines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vasystem.api.v2.AirlinesService/ListAirlines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirlinesServiceServer).ListAirlines(ctx, req.(*ListAirlinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AirlinesService_ServiceDesc is the grpc.ServiceDesc for AirlinesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AirlinesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vasystem.api.v2.AirlinesService",
	HandlerType: (*AirlinesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAirlines",
			Handler:    _AirlinesService_ListAirlines_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/vasystem/api/v2/airlines.proto",
}
